apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: corelabs
  labels:
    app: identity
spec:
  type: NodePort
  selector:
    app: identity
  ports:
    - name: http
      port: 4100
      targetPort: 4100
      protocol: TCP
status:
  loadBalancer: {}
